### PR TITLE
Progress toward working output

### PR DESCRIPTION
**Pull request by raphlinus**
This PR contains a whole bunch of code toward outputting a solid red screen, but it doesn't work. I haven't had time (and am thin on tools) to track down what's wrong. So consider this a checkpoint.

There are some things that are not great about the code. Having tried to use rp2040-hal to set up the DMA, I now think it would be better to use a pac, as we need special features like multi-channel trigger.

The code feels like it has way too many generics. I have a feeling that can be cleaned up with relatively minor refactoring.

### CODE REVIEW

**Comment by DusterTheFirst** [comment]
A first problem I have noticed is the clock speed is not changing to 252000 kHz. The log output from the pico shows the clock still at 125000 kHz.
image

**Comment by DusterTheFirst** [comment]
Ah, this seems to come from pico-sdk using crystal_freq_khz, where your implementation is using crystal_freq_mhz

```c
uint crystal_freq_khz = clock_get_hz(clk_ref) / 1000;
```

```rust
let crystal_freq_mhz: u32 = XOSC_CRYSTAL_FREQ / 1_000_000;
```

Refactoring the check_sys_clock_khz function to make use of fugit to utilize the type system for rate conversions I end up with this

```rust
const PICO_PLL_VCO_MIN_FREQ: MegahertzU32 = MegahertzU32::MHz(750);
const PICO_PLL_VCO_MAX_FREQ: MegahertzU32 = MegahertzU32::MHz(1600);

/// Determine PLL parameters for target frequency
///
/// Logic is adapted from check_sys_clock_khz in pico-sdk
fn check_sys_clock_khz(requested_freq: KilohertzU32) -> Option<ClockCfg> {
    let crystal_freq: KilohertzU32 = XOSC_CRYSTAL_FREQ.Hz();

    // Its called a feedback divider but it really is a clock multiplier
    // see 2.18.2 in rp2040-datasheet.pdf
    for feedback_divider in (16..=320).rev() {
        let vco_freq: KilohertzU32 = feedback_divider * crystal_freq;

        // Stop the loop since all consecutive numbers will also be less than this
        if vco_freq < PICO_PLL_VCO_MIN_FREQ {
            break;
        }

        if vco_freq > PICO_PLL_VCO_MAX_FREQ {
            continue;
        }

        for post_div1 in (1..=7).rev() {
            for post_div2 in (1..=post_div1).rev() {
                let divider = post_div1 * post_div2;

                let output_frequency: KilohertzU32 = vco_freq / divider;

                // Doing this instead of % to work around https://github.com/korken89/fugit/issues/41
                // Ensure the vco_freq is divisible by the clock dividers
                let vco_freq_divisible = output_frequency * divider == vco_freq;

                if output_frequency == requested_freq && vco_freq_divisible {
                    return Some(ClockCfg {
                        vco_freq,
                        post_div1,
                        post_div2,
                    });
                }
            }
        }
    }

    None
}
```

I do not currently have a setup to test the DVI output on a monitor, but from the probe-run output the frequency is being correctly updated now.

image


I have all of these changes in a commit on your branch. What would be the best way to downstream them to you? merge this commit and apply my changes on top of that? or apply my changes to your branch directly?

**Comment by raphlinus** [comment]
Thanks for looking into this! I'm sure there are other problems.

It's your repo, and I don't have super strong preferences, especially because the code is not in working state now. As a default, I'd say merge early and commit improvements laters as a separate PR, as this would give newcomers the freshest state of the code, but I don't think it matters much, so I'd be happy with other choices.

**Comment by DusterTheFirst** [comment]
Apologies to resurrect this. But looking at the popcnt function, it seems to re-implement the core library's [`u8::count_ones`](https://doc.rust-lang.org/std/primitive.u8.html#method.count_ones). Looking at the output of `rustc  --target=thumbv6m-none-eabi -O` on these two functions below gives the following assembly.

```rs
#![no_std]

pub fn popcnt_byte_1(byte: u32) -> u32 {
    let a = ((byte >> 1) & 0x55) + (byte & 0x55);
    let b = ((a >> 2) & 0x33) + (a & 0x33);
    ((b >> 4) + b) & 0xf
}

pub fn popcnt_byte_2(byte: u32) -> u32 {
    (byte as u8).count_ones()
}
```

```asm
; 15 instructions
example::popcnt_byte_1:
        movs    r1, #85
        lsrs    r2, r0, #1
        ands    r0, r1
        ands    r2, r1
        adds    r0, r2, r0
        movs    r1, #51
        lsrs    r2, r0, #2
        ands    r0, r1
        ands    r2, r1
        adds    r0, r2, r0
        lsrs    r1, r0, #4
        adds    r1, r1, r0
        movs    r0, #15
        ands    r0, r1
        bx      lr

; 14 instructions
example::popcnt_byte_2:
        lsrs    r1, r0, #1
        movs    r2, #85
        ands    r2, r1
        subs    r0, r0, r2
        movs    r1, #51
        lsrs    r2, r0, #2
        ands    r0, r1
        ands    r2, r1
        adds    r0, r0, r2
        lsrs    r1, r0, #4
        adds    r1, r0, r1
        movs    r0, #15
        ands    r0, r1
        bx      lr
```

The core libraries implementation looks like it beats the handmade one by one cycle. Removing the cast to a `u8` in the second function produces worse assembly, but since the implementation only counts the lower 8 bits anyways a cast to a u8 should not change the behavior.

Is there any reason that I am missing that makes `popcnt_byte_1` a better choice over `popcnt_byte_2`? I am also a bit caught off by the use of `u32`s to represent bytes and TMDS symbols instead of `u8`s and `u16`s repectively. Could you also shed light on that choice?

**Comment by raphlinus** [comment]
I can explain my thinking. Basically I was thinking about the armv6 thumb asm that I wanted, and worked backwards from there. Registers are of course 32 bit. A potential risk of using u8 and u16 is that you get extra UXTB and UXTH instructions that aren't needed.

Looking at the code, it's similar. I like the `byte - ((byte >> 1) & 0x55)` trick, I hadn't seen that before. I am impressed that the code is so optimized. Other than that, as you can see, the code is for all practical purposes identical.

As a philosophical matter, what I *generally* prefer is stating the intent of the code as clearly as possible, so the compiler has what it needs to generate optimum code. In this case, that would be the use of u8 types and popcnt. However, not for this particular thing, but for other bit wrangling, I've seen results come out of llvm that are considerably worse than hand-tuned asm, so that decreased my trust that the compiler will do the right thing. At that time, I was looking more at C than Rust, so one consequence is that I could also look at gcc results (generally better, especially for code size).

So absolutely, if asm confirms that the compiler is generating good code, I'm in favor.

**Pull request merged**
